version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:bionic"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install dependencies
          command: 'apt-get update && apt-get install -y python3-pip python3-yaml git curl cmake gcc g++ libgtest-dev libboost-all-dev lcov && pip3 install cpp-coveralls'
      - run:
          name: Install gtest
          command: 'cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib'
      - run:
          name: Install kindr
          command: |
            git clone https://github.com/ANYbotics/kindr.git
            cd kindr
            git checkout 1.1.3
            mkdir build
            cd build
            cmake ..
            sudo make install
      - run:
          name: CMake
          command: 'mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug'
      - run:
          name: Build
          command: 'cd build && make'
      - run:
          name: Test
          command: 'cd build && make test'
      - run:
          name: Codecov
          command: curl -s https://codecov.io/bash | bash
      - run:
          name: Coveralls
          command: /usr/local/bin/coveralls --exclude lib --exclude tests --exclude /usr/include/c++ --exclude /usr/include/boost --gcov-options '\-lp'
