version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:bionic"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install dependencies
          command: 'apt-get update && apt-get install -y git curl nodejs npm cmake gcc g++ libgtest-dev libboost-all-dev libeigen3-dev lcov libgoogle-glog-dev && sudo npm install coveralls --save-dev'
      - run:
          name: Install gtest
          command: 'cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib'
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: CMake
          command: 'mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug'
      - run:
          name: Build
          command: 'cd build && make'
      - run:
          name: Test
          command: 'cd build && make test'
      - run:
          name: Codecov
          command: curl -s https://codecov.io/bash | bash
      - run:
          name: Coveralls
          command: 'cd build && lcov --directory test --zerocounters && lcov --directory test --capture --output-file lcov.info && cat ./lcov.info | ./node_modules/coveralls/bin/coveralls.js
