version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:bionic"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing curl
          command: 'apt-get update && apt-get install -y curl'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install gtest
          command: 'apt-get update && apt-get install -y libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib'
      - run:
          name: Install boost
          command: 'apt-get update && apt-get install -y libboost-all-dev'
      - run:
          name: Install lcov
          command: 'apt-get update && apt-get install -y lcov'
      - run:
          name: Creating build directory
          command: 'mkdir build'
      - run:
          name: CMake
          command: 'cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug'
      - run:
          name: Build
          command: 'cd build && make'
      - run:
          name: Test
          command: 'cd build && make test'
      - run: curl -s https://codecov.io/bash | bash
      - run:
          name: Install coveralls
          command: 'apt-get update && apt-get install -y python3-pip locate python3-yaml && pip3 install cpp-coveralls'
      - run: updatedb &&  locate coveralls
      - run: /usr/local/bin/coveralls --exclude lib --exclude tests --exclude /usr/include/c++ --exclude /usr/include/boost --gcov-options '\-lp'
